import React, { createContext } from "react";

interface petsContext {
  token: string | null;
  pets: {}[] | null;
  setPets: (pets: {}[]) => void | null;
  page: number;
  setPage: (page: number) => void | null;
  totalResults: number;
  setTotalResults: (totalResults: number) => void | null;
  breeds: {}[];
  setBreeds: (breeds: {}[]) => void | null;
  filteredBreed: string;
  setFilteredBreed: (filteredBreed: string | null) => void | null;
  url: string;
  setUrl: (url: string) => void | null;
  id: number;
  setId: (id: number) => void | null;
  zip: string;
  setZip: (zip: string) => void | null;
  pet: string;
  setPet: (pet: string) => void | null;
  selectedBreed: string;
  setSelectedBreed: (selectedBreed: string) => void | null;
  filteredPage: number;
  setFilteredPage: (filteredPage: number) => void | null;
  name: string;
  setName: (name: string) => void | null;
  image: string;
  setImage: (image: string) => void | null;
  images: {}[] | [];
  setImages: (images: {}[] | [] | null) => void | null;
  gender: string;
  setGender: (gender: string | null) => void | null;
  desc: string;
  setDesc: (desc: string) => void | null;
  breed: string;
  setBreed: (breed: string) => void | null;
  status: string;
  setStatus: (status: string) => void | null;
  attributes: {};
  setAttributes: (attributes: {}) => void | null;
  location: string;
  setLocation: (location: string) => void | null;
  petUrl: string;
  setPetUrl: (petUrl: string) => void | null;
  size: string;
  setSize: (size: string) => void | null;
  trained: string;
  setTrained: (trained: string) => void | null;
  organizations: {}[];
  setOrganizations: (organizations: {}[]) => void | null;
  orgZip: string;
  setOrgZip: (orgZip: string) => void;
  loadedOrganizations: boolean;
  setLoadedOrganizations: (loadedOrganizations: boolean) => void | null;
  age: string;
  setAge: (age: string) => void | null;
  likes: {}[] | [];
  setLikes: (likes: {}[] | []) => void | null;
}

const PetContext = createContext<petsContext>({});

export default PetContext;
